version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install boto3
  build:
    commands:
      - echo Building the Lambda package...
      - zip -r lambda_function.zip lambda_function.py

artifacts:
  files:
    - lambda_function.zip
